#!/bin/sh

# rm -f src/Makevars src/makevars.h
rm -f config.log config.status aclocal.m4 \
    src/*.o src/*.a src/*.d src/*.dll src/*.dylib \
    vignettes/*.aux \
    vignettes/*.log \
    vignettes/*.out \
    vignettes/*.tex \
    vignettes/*.bbl \
    vignettes/*.blg \
    vignettes/*.toc \
    vignettes/*.knit.md \
    vignettes/*.utf8.md \
    icd_*.tar.gz \
    icd-0*.log 

rm -rf autom4te.cache \
    icd.Rcheck
