#!/bin/sh

# if/when move away from configure script, don't delete the
# legitimate files
test -f configure && rm -f src/Makevars

rm -f config.log config.status aclocal.m4 \
    src/*.o src/*.a src/*.d \
    vignettes/*.aux \
    vignettes/*.log \
    vignettes/*.out \
    vignettes/*.tex \
    vignettes/*.bbl \
    vignettes/*.blg \
    vignettes/*.toc \
    vignettes/*.knit.md \
    vignettes/*.utf8.md \
    icd_*.tar.gz \
    icd-0*.log

rm -rf autom4te.cache \
    icd.Rcheck
