context("comorbidities, generally slow tests")

set.seed(1441)
n <- 500
np <- round(n/20) # icd9 codes per patients

randomShortIcd9 <- as.character(floor(runif(min = 10000, max = 99999, n = n)))
randomSampleAhrq <- sample(unname(c(ahrqComorbid, recursive = TRUE)), replace = TRUE, size = n)
fewIcd9 <- c("27801", "7208", "25001", "34400", "4011", "4011")

patientData <- data.frame(
  visitId = c(1000, 1000, 1000, 1001, 1001, 1002),
  icd9 = fewIcd9,
  poa = factor(c("Y", "N", "Y", "N", "Y", "N"))
)

simplePoaPatients <- data.frame(
  visitId = c("v1", "v2", "v3", "v4"),
  icd9 = c("39891", "39790", "41791", "4401"),
  poa = c("y", "N", "E", NA_character_), # should tolerate mixed case
  stringsAsFactors = FALSE
)

# multiple codes for POA and not POA, bad POA input. Throw in some invalid ICD9 codes
complexPoaPatients <- data.frame(
  visitId = c("v1", "v1", "v1", "v2", "v2", "v3", "v3"),
  icd9 = c("39891", "39891", "39790", "41791", "41791", "41791", "4401"),
  poa = c("Y", "n", NA_character_, "E", NA_character_, "paris", ""),
  stringsAsFactors = FALSE
)

randomPatients <- data.frame(
  visitId = sample(seq(1, np), replace = TRUE, size=n),
  icd9 = randomShortIcd9,
  poa = as.factor(sample(x=c("Y", "N", "n", "n", "y", "X", "E", "", NA), replace = TRUE, size=n))
)

# random patients with icd9 codes selected from ahrq data
randomPatientsAhrqIcd9 <- randomPatients
randomPatientsAhrqIcd9[["icd9"]] <- randomSampleAhrq

testTwenty <- structure(
  list(visitId = c(207210584L, 207210584L, 207210584L,
                   207210584L, 207210584L, 207210600L, 207210600L,
                   207210600L, 207210600L, 207210600L, 207210600L,
                   207210600L, 207210600L, 207210600L, 207210600L,
                   207210600L, 207210600L, 207210600L, 207210618L, 207210618L),
       icd9Code = structure(
         c(17L, 1L, 14L, 10L, 13L, 11L, 8L, 6L,
           18L, 2L, 7L, 19L, 3L, 5L, 20L, 16L, 12L, 4L, 15L, 9L),
         .Label = c("04104", "1912", "2449", "2949", "29680", "4254", "4371", "4530",
                    "5070", "59370", "5990", "71595", "74689", "7757", "85226",
                    "V153", "77182", "45341", "78097", "V1529"), class = "factor"),
       poa = c("N", "N", "N", "Y", "Y", "Y", "Y", "Y", "Y", "Y",
               "Y", "Y", "Y", "Y", "E", "E", "Y", "Y", "Y", "N")),
  .Names = c("visitId", "icd9Code", "poa"),
  row.names = 5000000:5000019,
  class = "data.frame")

test_that("no NA values in the co-morbidity lists", {
  expect_false(any(is.na(unlist(unname(ahrqComorbid)))))
  expect_false(any(is.na(unlist(unname(ahrqComorbidAll)))))
  expect_false(any(is.na(unlist(unname(quanDeyoComorbid)))))
  expect_false(any(is.na(unlist(unname(quanElixhauserComorbid)))))
  expect_false(any(is.na(unlist(unname(elixhauserComorbid)))))
})

test_that("built-in icd9 to comorbidity mappings are all valid", {
  expect_true(icd9ValidMappingShort(ahrqComorbid))
  expect_true(icd9ValidMappingShort(quanDeyoComorbid))
  expect_true(icd9ValidMappingShort(quanElixhauserComorbid))
  expect_true(icd9ValidMappingShort(elixhauserComorbid))
})

test_that("ahrq icd9 mappings are all generated from the current generation code", {
  expect_identical(ahrqComorbid, parseAhrqSas(condense = FALSE, save = FALSE, returnAll = FALSE)) # same but from source data. Should be absolutely identical.
  expect_identical(ahrqComorbidAll, parseAhrqSas(condense = FALSE, save = FALSE, returnAll = TRUE)) # same but from source data. Should be absolutely identical.
})
test_that("quan charlson icd9 mappings are all generated from the current generation code", {
  expect_identical(quanDeyoComorbid, parseQuanDeyoSas(condense = FALSE, save = FALSE))
})
test_that("quan elixhauser icd9 mappings are all generated from the current generation code", {
  expect_identical(quanElixhauserComorbid, parseQuanElixhauser(condense = FALSE, save = FALSE))
})
test_that("elixhauser icd9 mappings are all generated from the current generation code", {
  expect_identical(elixhauserComorbid, parseElixhauser(condense = FALSE, save = FALSE))
})

test_that("can condense the big lists of comorbidities without errors", {
  # this is a useful test because the data weren't generated by just expanding
  # base ranges (which is how the condense works in reverse)
  ahrq <- lapply(ahrqComorbid, icd9CondenseShort)
  quanDeyo <- lapply(quanDeyoComorbid, icd9CondenseShort)
  quanElixhauser <- lapply(quanElixhauserComorbid, icd9CondenseShort)
  elixhauser <- lapply(elixhauserComorbid, icd9CondenseShort)
  expect_is(ahrq, class = "list")
  expect_is(elixhauser, class = "list")
  expect_is(quanDeyo, class = "list")
  expect_is(quanElixhauser, class = "list")
  # the comorbidity mappings save in \code{data} should not be condensed.
  expect_false(identical(ahrq, ahrqComorbid))
  expect_false(identical(elixhauser, elixhauserComorbid))
  expect_false(identical(quanDeyo, quanDeyoComorbid))
  expect_false(identical(quanElixhauser, quanElixhauserComorbid))
})

test_that("ahrq make sure all the children are listed in the saved data.", {
  ahrq <- lapply(ahrqComorbid, icd9ChildrenShort)
  expect_equal(ahrq, ahrqComorbid)
})
test_that("elixhauser make sure all the children are listed in the saved data.", {
  elixhauser <- lapply(elixhauserComorbid, icd9ChildrenShort)
  expect_equal(elixhauser, elixhauserComorbid)
})
test_that("quan charlson make sure all the children are listed in the saved data.", {
  quanDeyo <- lapply(quanDeyoComorbid, icd9ChildrenShort)
  expect_equal(quanDeyo, quanDeyoComorbid)
})
test_that("quan elixhauser make sure all the children are listed in the saved data.", {
  quanElixhauser <- lapply(quanElixhauserComorbid, icd9ChildrenShort)
  expect_equal(quanElixhauser, quanElixhauserComorbid)
})

test_that("condense an ICD-9 code set to minimal group", {
  expect_equal(sort(icd9CondenseShort("98799" %i9s% "98901")), sort(c("98799", "988", "98900", "98901")))
  # TODO: more tests
})


# test_that("AHRQ interpretation at least returns something reasonable", {
#   result <- parseAhrqSas(sasPath = system.file("extdata", "comformat2012-2013.txt", package="icd9"), save = FALSE)
#   expect_that(result, is_a("list"))
#   expect_true(length(result) > 10)
# })

test_that("HTN subgroups all worked", {
  # pick one subcategory
  expect_true(all(ahrqComorbidAll$HTNPREG %in% ahrqComorbid[["HTN"]]))

  # and we didn't drop any:
  expect_true(all(ahrqComorbidAll$HTNCX %in% ahrqComorbid[["HTNcx"]]))
  expect_true(all(ahrqComorbidAll$CHF %in% ahrqComorbid[["CHF"]]))
  expect_true(all(ahrqComorbidAll$RENLFAIL %in% ahrqComorbid[["Renal"]]))

})

test_that("icd9 codes to comorbities", {

  # TODO write the test!

})

test_that("icd9 comorbidities are created correctly, and logical to binary conversion ok", {

  ptdf <- icd9Comorbidities(icd9df = patientData, icd9Mapping = ahrqComorbid, visitId = "visitId")

  expect_equal(names(ptdf), c("visitId", names(ahrqComorbid)))

  expect_true(all(sapply(names(ahrqComorbid), function(x) class(ptdf[, x])) == "logical"))
  ptdflogical <- logicalToBinary(ptdf)
  expect_true(all(sapply(names(ahrqComorbid), function(x) class(ptdflogical[, x])) == "integer"))
  # do not expect all the rest of patient data to be returned - we aren't
  # responsible for aggregating other fields by visitId!
  expect_equal(dim(ptdf), c(length(unique(patientData[["visitId"]])), 1 + length(ahrqComorbid)))
  expect_true(all(names(ptdf) %in% c("visitId", names(ahrqComorbid))))
  expect_true(all(names(ptdflogical) %in% c("visitId", names(ahrqComorbid))))

  expect_equal(
    logicalToBinary(data.frame(a = c("jack", "hayley"), b = c(TRUE, FALSE), f = c(TRUE, TRUE))),
    data.frame(a = c("jack", "hayley"), b = c(1, 0), f = c(1, 1))
  )

})

test_that("Charlson Deyo mapping doesn't double count disease with multiple severities", {
  expect_false(any(quanDeyoComorbid[["Mild Liver Disease"]] %in% quanDeyoComorbid[["Moderate or Severe Liver Disease"]] ))
  expect_false(any(quanDeyoComorbid[["Cancer"]] %in% quanDeyoComorbid[["Metastatic Carcinoma"]] ))
  expect_false(any(quanDeyoComorbid[["Diabetes without complications"]] %in% quanDeyoComorbid[["Diabetes with complications"]] ))
})

test_that("Elixhauser mapping doesn't double count disease with multiple severities", {
  expect_false(any(quanElixhauserComorbid[["dm.uncomp"]] %in% quanElixhauserComorbid[["dm.comp"]] ))
  expect_false(any(quanElixhauserComorbid[["solid.tumor"]] %in% quanElixhauserComorbid[["mets"]] ))
  expect_false(any(elixhauserComorbid[["dm.uncomp"]] %in% elixhauserComorbid[["dm.comp"]] ))
  expect_false(any(elixhauserComorbid[["solid.tumor"]] %in% elixhauserComorbid[["mets"]] ))
  expect_false(any(ahrqComorbid[["DM"]] %in% ahrqComorbid[["DMCX"]] ))
  expect_false(any(ahrqComorbid[["TUMOR"]] %in% ahrqComorbid[["METS"]] ))
})


test_that("filter POA - not a data frame", {
  expect_error(icd9FilterPoaNo(list(pollo = "loco")))
  expect_error(icd9FilterPoaNotYes(visitId=c("1","2"), icd9 = c("1","2"), poa = c("Y","N")))
})

test_that("filter POA - no poa field", {
  expect_error(icd9FilterPoaYes(simplePoaPatients[1:2]))
})

test_that("filter POA - generic func - invalid poa type", {
  expect_error(icd9FilterPoa(icd9df = simplePoaPatients, poaField = "poa", poa = "not an option"))
  expect_error(icd9FilterPoa(icd9df = simplePoaPatients, poaField = "poa", poa = ""))
  expect_error(icd9FilterPoa(icd9df = simplePoaPatients, poaField = "poa", poa = NA))
})

test_that("filter POA - wrong name poa field", {
  pd <- simplePoaPatients
  names(pd) <- c("visitId", "icd9", "achilleus")
  expect_error(icd9FilterPoaYes(pd, poaField = "poa"))
  expect_error(icd9FilterPoaYes(pd, poaField = "odysseus"))
  expect_error(icd9FilterPoaYes(pd))
})

test_that("filter POA - poa is factor", {
  # POA flag is an obvious case for using factors. Not sure if it saves much
  # memory, and it certainly risks screwing up the analysis with obscure and
  # difficult to debug errors. ICD-9 code is also factor fodder, and likely to
  # be highly repeated over millions of patients, but I've resisted its charms
  # thus far.
  simplePoaPatients$poa <- factor(simplePoaPatients$poa) # just within this closure
  names(simplePoaPatients)[3] = "poa"
  complexPoaPatients$poa <- factor(complexPoaPatients$poa) # just within this closure
  names(complexPoaPatients)[3] = "poa"

  # row names are preserved here: probably not important, but a little annoying
  expect_identical(icd9FilterPoaYes(simplePoaPatients), simplePoaPatients[1, 1:2])
  expect_identical(icd9FilterPoaNotYes(simplePoaPatients), simplePoaPatients[-1, 1:2])
  expect_identical(icd9FilterPoaNo(simplePoaPatients), simplePoaPatients[2, 1:2])
  expect_identical(icd9FilterPoaNotNo(simplePoaPatients), simplePoaPatients[-2, 1:2])

  expect_identical(icd9FilterPoaYes(complexPoaPatients), complexPoaPatients[1, 1:2])
  expect_identical(icd9FilterPoaNotYes(complexPoaPatients), complexPoaPatients[-1, 1:2])
  expect_identical(icd9FilterPoaNo(complexPoaPatients), complexPoaPatients[2, 1:2])
  expect_identical(icd9FilterPoaNotNo(complexPoaPatients), complexPoaPatients[-2, 1:2])
})

test_that("filter POA - poa is vector", {
  expect_identical(icd9FilterPoaYes(simplePoaPatients), simplePoaPatients[1, 1:2])
  expect_identical(icd9FilterPoaNotYes(simplePoaPatients), simplePoaPatients[-1, 1:2])
  expect_identical(icd9FilterPoaNo(simplePoaPatients), simplePoaPatients[2, 1:2])
  expect_identical(icd9FilterPoaNotNo(simplePoaPatients), simplePoaPatients[-2, 1:2])

  expect_identical(icd9FilterPoaYes(complexPoaPatients), complexPoaPatients[1, 1:2])
  expect_identical(icd9FilterPoaNotYes(complexPoaPatients), complexPoaPatients[-1, 1:2])
  expect_identical(icd9FilterPoaNo(complexPoaPatients), complexPoaPatients[2, 1:2])
  expect_identical(icd9FilterPoaNotNo(complexPoaPatients), complexPoaPatients[-2, 1:2])

})

test_that("filter POA - poa upper and lower case", {
 smpl <- simplePoaPatients
 smpl[["poa"]] <- c("Y", "n", "e", NA)
 expect_identical(icd9FilterPoaNo(smpl), icd9FilterPoaNo(simplePoaPatients))
})

test_that("filter POA - just Y and N should be complementary", {
  # take any data frame to start out:
  dfrm <- testTwenty;
  dfrm <- dfrm[dfrm[["poa"]] %in% c("Y", "N", "y", "n"),]
  expect_identical(icd9FilterPoaNo(dfrm),  icd9FilterPoaNotYes(dfrm))
  expect_identical(icd9FilterPoaYes(dfrm), icd9FilterPoaNotNo(dfrm))
})
