// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef __icd9_h__
#define __icd9_h__

#include "icd9_RcppExports.h"

#endif // __icd9_h__
