#!/usr/bin/env bash
#shellcheck disable=SC2034
#MAKEFLAGS="CXXFLAGS=-Wno-unused-parameter\\ -Wno-unused-variable\\ -Wno-ignored-attributes\\ -Wno-cast-function-type\\ -Wno-unknown-warning-option\\ -Wno-unknown-pragma"
#
# --enable-icd-shutup is more targetted...
#MAKEFLAGS="CXXFLAGS=-w CXX11FLAGS=-w CXX14FLAGS=-w CXX17FLAGS=-w CXX20FLAGS=-w CFLAGS=-w"

_R_CHECK_ASCII_DATA_="FALSE"
_R_CHECK_PKG_SIZES_="FALSE"
_R_CHECK_COMPILATION_FLAGS_="FALSE"
_R_CHECK_CRAN_INCOMING_="FALSE"
_R_CHECK_CRAN_INCOMING_REMOTE_="FALSE"
_R_CHECK_DEPENDS_ONLY_="TRUE"
_R_CHECK_DOC_SIZES2_="FALSE"
_R_CHECK_DOC_SIZES_="FALSE"
