#!/bin/bash
# http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

ICD_HOME=${ICD_HOME:-"$HOME/rprojects/icd"}
pushd "$ICD_HOME"

INSTR_ATSTART="no"
VALGRIND_CMD="valgrind --tool=callgrind --simulate-cache=yes --instr-atstart=$INSTR_ATSTART --separate-threads=no"
R --vanilla -d "$VALGRIND_CMD" "$@"
popd

