# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

icd9MajMinToCode <- function(mjr, mnr, isShort) {
    .Call('icd9_icd9MajMinToCode', PACKAGE = 'icd9', mjr, mnr, isShort)
}

#' @name icd9MajMinToShort
#' @title icd9MajMinToShort
#' @export
icd9MajMinToShort <- function(mjr, mnr) {
    .Call('icd9_icd9MajMinToShort', PACKAGE = 'icd9', mjr, mnr)
}

#' @name icd9MajMinToDecimal
#' @title icd9MajMinToDecimal
#' @export
icd9MajMinToDecimal <- function(mjr, mnr) {
    .Call('icd9_icd9MajMinToDecimal', PACKAGE = 'icd9', mjr, mnr)
}

#' @name icd9PartsToShort
#' @title icd9PartsToShort
#' @export
icd9PartsToShort <- function(parts) {
    .Call('icd9_icd9PartsToShort', PACKAGE = 'icd9', parts)
}

#' @name icd9PartsToDecimal
#' @title icd9PartsToDecimal
#' @export
icd9PartsToDecimal <- function(parts) {
    .Call('icd9_icd9PartsToDecimal', PACKAGE = 'icd9', parts)
}

#' @name icd9MajMinToParts_df
#' @title icd9MajMinToParts_df
#' @description Convert vectors of major and minor components into a data frame with a column for major and a column for minor.
#' This is 20x faster in this C++ implementation, and important for a very frequently used function.
#' @import Rcpp
#' @export
icd9MajMinToParts <- function(mjr, mnr) {
    .Call('icd9_icd9MajMinToParts', PACKAGE = 'icd9', mjr, mnr)
}

#' @name icd9MajMinToParts
#' @title icd9MajMinToParts
#' @description Convert vectors of major and minor components into a data frame with a column for major and a column for minor.
#' This is probably just as quick in R, but I think I may rely on having a data frame output (which is slower to construct in R)
#' @import Rcpp
#' @export
icd9MajMinToParts_list <- function(mjr, mnr) {
    .Call('icd9_icd9MajMinToParts_list', PACKAGE = 'icd9', mjr, mnr)
}

#' @name icd9MajMinToParts_slower
#' @title icd9MajMinToParts_slower
#' @description Convert vectors of major and minor components into a data frame with a column for major and a column for minor.
#' This is slightly slower than the R implementation. using Rcpp11 std::to_string is even slower than this.
#' @import Rcpp
#' @export
icd9MajMinToParts_slower <- function(mjr, mnr) {
    .Call('icd9_icd9MajMinToParts_slower', PACKAGE = 'icd9', mjr, mnr)
}

#' @name icd9ShortToParts_cpp_slow
#' @title extract major and minor parts of a decimal ICD-9 code
#' @description accepts Vxxxx Exxxx or xxxxx
#' @template icd9-short
#' @param minorEmpty vector of length one, to be used in place of
#'   minor part of zero. Defaults to ""
#' @template invalid
#' @return data.frame with two columns. At least the minor part must be
#'   character, because "03" is different to "3", but "30" is the same as "3"
#' @keywords  manip
#' @export
icd9ShortToParts_cpp_slow <- function(icd9Short, minorEmpty = "") {
    .Call('icd9_icd9ShortToParts_cpp_slow', PACKAGE = 'icd9', icd9Short, minorEmpty)
}

#' @name icd9ShortToParts
#' @title extract major and minor parts of a decimal ICD-9 code
#' @description accepts Vxxxx Exxxx or xxxxx. This version just beats native R, but lowerhead for calls.
#' @template icd9-short
#' @param minorEmpty vector of length one, to be used in place of
#'   minor part of zero. Defaults to ""
#' @template invalid
#' @return data.frame with two columns. At least the minor part must be
#'   character, because "03" is different to "3", but "30" is the same as "3"
#' @keywords  manip
#' @export
icd9ShortToParts <- function(icd9Short, minorEmpty = "") {
    .Call('icd9_icd9ShortToParts', PACKAGE = 'icd9', icd9Short, minorEmpty)
}

#' @name icd9ShortToParts_cpp_test
#' @title extract major and minor parts of a decimal ICD-9 code
#' @description accepts Vxxxx Exxxx or xxxxx. This version just beats native R...
#' @template icd9-short
#' @param minorEmpty vector of length one, to be used in place of
#'   minor part of zero. Defaults to ""
#' @template invalid
#' @return data.frame with two columns. At least the minor part must be
#'   character, because "03" is different to "3", but "30" is the same as "3"
#' @keywords  manip
#' @export
icd9ShortToParts_cpp_test <- function(icd9Short, minorEmpty = "") {
    .Call('icd9_icd9ShortToParts_cpp_test', PACKAGE = 'icd9', icd9Short, minorEmpty)
}

#' @name icd9ShortToDecimal
#' @title icd9ShortToDecimal
#' @export
icd9ShortToDecimal <- function(x) {
    .Call('icd9_icd9ShortToDecimal', PACKAGE = 'icd9', x)
}

